### PR TITLE
MAINT: Bump to v0.6.4

### LINKED ISSUE #42: Many files acciendtally incldued creating conflicts with other packages
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

image

The folders:

* `benchmarks`
* `docs`
* `test`

should not be included

### Installed packages

```shell
* conda-forge/linux-64::keras-3.3.3-pyhd8ed1ab_0
* conda-forge/linux-64::asv-0.6.3-py310hc6cd4ac_0

ClobberError: The package 'conda-forge/linux-64::asv-0.6.3-py310hc6cd4ac_0' cannot be installed due to a
path collision for 'lib/python3.10/site-packages/benchmarks/__init__.py'.
This path already exists in the target prefix, and it won't be removed by
an uninstall action in this transaction. The path appears to be coming from
the package 'conda-forge/noarch::keras-3.3.3-pyhd8ed1ab_0', which is already installed in the prefix.


ClobberError: The package 'conda-forge/linux-64::asv-0.6.3-py310hc6cd4ac_0' cannot be installed due to a
path collision for 'lib/python3.10/site-packages/benchmarks/__pycache__/__init__.cpython-310.pyc'.
This path already exists in the target prefix, and it won't be removed by
an uninstall action in this transaction. The path appears to be coming from
the package 'conda-forge/noarch::keras-3.3.3-pyhd8ed1ab_0', which is already installed in the prefix.
```

### Environment info

```shell
linux64
```

### PR DESCRIPTION
**Pull request by HaoZeke**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

Closes #42.

### CODE REVIEW

**Comment by HaoZeke** [comment]
@conda-forge-admin, please rerender

**Comment by mattip** [comment]
LGTM. Any idea why #45 is failing to apply patches but this PR succeeds?

**Comment by HaoZeke** [comment]
> LGTM. Any idea why #45 is failing to apply patches but this PR succeeds?

@hmaarrfk added the changes in the patches upstream in asv and so they aren't required anymore (and are removed in this PR).

**Comment by mattip** [comment]
Thanks @HaoZeke , @hmaarrfk

**Pull request merged**
