### PR TITLE
Require setuptools

### PR DESCRIPTION
**Pull request by saraedum**
setuptools are a runtime requirement, without them
```
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'
```

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender

**Comment by saraedum** [comment]
Strangely, the failing OSX builds have no build on Azure. Let's rebuild and see if that helps.

**Comment by saraedum** [comment]
@CJ-Wright this looks good to me now. Can this be merged?

**Comment by CJ-Wright** [comment]
LGTM

**Pull request merged**
